---
title: "Final Project Proposal"
author: "Vincent Chau, Christie Wong, Jimmy Leng, Arsenii Vasilev"
date: "2026-02-01"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Problem Statement and Motivation

- define problem & research questions
  How do outside factors delay international flights?
- explain why the problem is important and interesting
  The problem is important because international aviation contributes trillions of dollars to the GDP of many countires, creating economic growth. Furthermore, many political figures rely on flights to travel from place to place. Having an understanding in why flights may be delayed can help prevent timimg issues as well as potentially save lives. This topic is interesting because we are discovering potential reasons in what factors are the main factors of delays. If we were to pinpoint specific indicators, we could possibly create predictive models based off these factors to ensure timely flights and improve efficiency in the aviation industry. 
- outline specific goals/hypotheses to be addressed
  We hypothesize that a combination of popular vacation destinations along with seasonal holidays and extreme weather conditions are high contributors to flight delays. 
- key questions you plan to explore
  How does the weather of particular regions affect flight delays?
  How do holidays/popular vacation times affect flight delays?
  Do popular vacation locations mean an increase in flight delays?
  Do specific weather conditions and seasons delay flights more than others?
  Do flight delays occur due to their destination or the origin of the airport?
  
  
  


## Data Description

- identify dataset(s) to be used & cite data source/link
- highlight variables important to your research questions
- any data limitations? (ex: missing values)
- assess data cleanliness (describe cleaning plan)
- if using multiple datasets, how will you merge/integrate them?
- justify why the dataset(s) are sufficient to your research questions



## Exploratory Data Analysis (Extra Credit)

- include results from prelim EDA
- describe what insights EDA has provided for project


## Methodology & Analysis Plan

- describe analysis/modeling plan
- link methods directly to project objectives
- specify detailed techniques you plan to use (ex: visualization, modeling, evaluation methods)
- ensure methods are appropriate + thoughtfully chosen (not vague)
- include realistic work plan + timeline showing project feasibility


## Alternative Strategies & Backup Plans

- discuss potential pitfalls/challenges you might encounter and propose clear alternative strategies + back up plans
1. Incompleteness or inconsistency of data:
  Our dataset might be incomplete or have missing values, which could limit the scope of our analysis.
  Backup plan: We cna create proxy variables to approximate the factors of interest. For example, instead of using detailed wether conditions, we cna replace them with binary variable, that will indicate if wheather conditions were good (1) for flight departures or bad (0). On another hand we can try to replace all the missing values and do a thorough data cleaning. 
2. High correlation of individual factors:
  There might occur difficulties in isolating individual factors due to high correlation.
  Backup plan: We can use statistical controls and simplified models to reduce confounding effects. For example, we can compare holiday delays woth non-holiday delays, delays with good weather conditions and delays with bad weather conditions separately.
3. Extreme broadness of scope:
The scope of our current dataset might be too wide for us to make accurate analysis.
Backup plan: We can narrow down our analysis to a smaller set of factors or move the focus onto smaller range of time and etc.
- list 2-3 other ideas you have brainstormed, each with a couple bullet points of details
1. Yelp reviews analysis
* [Yelp dataset](https://www.yelp.com/dataset)
* Is there any correlation between bad reviews and area codes? Or how likely bad reviews? Or how often reviews include photos and are they mostly bad?
* Types of analysis: Spatial, classification, probability analysis.
2. Uber rides analysis
*[Uber pickups](https://www.kaggle.com/fivethirtyeight/uber-pickups-in-new-york-city)
* What is the average trip length? What are of NYC uses Uber more frequently? How long does average ride takes?
* Types of analysis: Temporal, spatial or trip efficiency analysis.








