---
title: "Final Project Report"
author: "Group 5 - VCAJ"
date: "2026-03-13"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Project Description
- Clearly defines primary research questions/objectives
- Project background and motivation
- Importance/relevance of problem
- Outlines expected outcomes, hypotheses, or analytical goals



## Data Description & Preparation
- Specifies datasets used + provides data source/link
- Describes structure of data + variables involved
- Identify variables relevant to research questions
- Discusses any data limitations, missing values, cleaning steps
- Explains integration approach if multiple datasets are used



## Exploratory Data Analysis
- Visualizations w/ clear titles + labels
- Examine trends, distributions, relationships
- Interpret EDA results + connect them to research goals



## Methodology & Analysis
- Explain choice of analytical/modeling methods
- Justify methods based on project goals + data type
- Identify predictors + outcomes clearly
- Address model assumptions and how they are assessed
- Demonstrates depth in connecting methods to research questions



## Model Implementation & Evaluation
- Uses appropriate model validation strategies (cross-validation and/or validation set approach)
- Employ relevant + justified performance metrics
- Clearly explains model performance + any tradeoffs
- Considers model complexity, overfitting, model selection


## Results & Discussion
- Results presented w/ interpretation in context
- Links results back to original questions/objectives.
- Discuss limitations, implications, potential real-world impact
- Offer thoughtful insights supported by evidence

## Data Description
  For our dataset, we used the “flights” and “weather” datasets from the “nycflights13” library. We decided that the important variables we wanted to look further into were month, day, year, destination, arrival delay, departure delay, temperature, precipitation, humidity, visibility, origin, and time. We decided to integrate the two datasets by the origin and time. Then we retained only the variables we considered important, as listed earlier, and used them to answer our questions. When looking at the dataset, we found some missing values, so we decided to remove any rows with NAs in any column. This reduced our observations from around 336k to 325k. 
  While working on the project, some limitations were encountered. Our first limitation was that we only had data from 2013, which means our dataset is limited to one year and includes only flights departing from NYC, so we can only analyze flights in NYC rather than flights across the whole country. One last limitation is that important data may have been missing or variables omitted.



## Team Member Contributions

* Vincent Chau - 
* Christie Wong - 
* Jimmy Ieng - 
* Arsenii Vasilev - 



